name: Build wheels

# on: [push, pull_request]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        container:
          image: quay.io/pypa/manylinux_2_34_x86_64
        include:
          # Specify architectures for Windows
          # - os: windows-latest
          #   arch: x64
          #   cibw_platform: windows
          # - os: windows-latest
          #   arch: x86
          #   cibw_platform: windows
          # Specify architectures for macOS
          # - os: macos-latest
          #   arch: x86_64
          #   cibw_platform: macos
          # - os: macos-latest
          #   arch: arm64
          #   cibw_platform: macos
          # Linux (defaults to x86_64)
          # - os: ubuntu-latest
          #   arch: x86_64
          #   cibw_platform: linux
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Specify the platform and architecture
          CIBW_PLATFORM: ${{ matrix.cibw_platform }}
          CIBW_ARCHS: ${{ matrix.arch }}
          # CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-*"
          CIBW_BUILD: "p39-*"

      # - name: Upload wheels
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: ./wheelhouse/*.whl
