name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]
        # container:
        #   image: quay.io/pypa/manylinux_2_34_x86_64
        # include:
          # Specify architectures for Windows
          # - os: windows-latest
          #   arch: x64
          #   cibw_platform: windows
          # - os: windows-latest
          #   arch: x86
          #   cibw_platform: windows
          # Specify architectures for macOS
          # - os: macos-latest
          #   arch: x86_64
          #   cibw_platform: macos
          # - os: macos-latest
          #   arch: arm64
          #   cibw_platform: macos
          # Linux (defaults to x86_64)
          # - os: ubuntu-latest
          #   arch: x86_64
          #   cibw_platform: linux
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Set up QEMU
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-qemu-action@v3

      - name: Build
        run: python -m cibuildwheel --output-dir dist

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*.whl

  # make_sdist:
  #   name: Make SDist
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       fetch-depth: 0  # Optional, use if you use setuptools_scm
  #       submodules: false  # Optional, use if you have submodules

  #   - name: Build SDist
  #     run: pipx run build --sdist

  #   - uses: actions/upload-artifact@v4
  #     with:
  #       name: cibw-sdist
  #       path: dist/*.tar.gz

  pypi-publish:
    needs: [build_wheels]
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment:
      name: pypi
      url: https://pypi.org/p/netlibpp
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      # retrieve your distributions here
      - name: Download Linux wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest
          path: dist

      - name: Download Windows wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest
          path: dist

      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos-latest
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  
