name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        # container:
        #   image: quay.io/pypa/manylinux_2_34_x86_64
        # include:
          # Specify architectures for Windows
          # - os: windows-latest
          #   arch: x64
          #   cibw_platform: windows
          # - os: windows-latest
          #   arch: x86
          #   cibw_platform: windows
          # Specify architectures for macOS
          # - os: macos-latest
          #   arch: x86_64
          #   cibw_platform: macos
          # - os: macos-latest
          #   arch: arm64
          #   cibw_platform: macos
          # Linux (defaults to x86_64)
          # - os: ubuntu-latest
          #   arch: x86_64
          #   cibw_platform: linux
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: false  # Optional, use if you have submodules

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz
    
  upload_all:
    needs: [build_wheels, make_sdist]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
